# Generated by Django 5.2.7 on 2025-11-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'ordering': ['sobrenome', 'nome'], 'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='idade',
        ),
        migrations.AddField(
            model_name='aluno',
            name='sobrenome',
            field=models.CharField(default='sobrenome', max_length=50, verbose_name='Sobrenome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
    ]
