# Generated by Django 5.2.7 on 2025-11-13 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_alter_aluno_options_remove_aluno_idade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('alunos', models.ManyToManyField(related_name='cursos', to='alunos.aluno')),
            ],
        ),
    ]
